# Introduction to Pandas

Similar to the import convention for NumPy (import numpy as np), the import convention for pandas is:

We'll be working with data set from Fortune magazine's Global 500 list 2017, which ranks the top 500 corporations worldwide by revenue.

## Pandas and Numpy

### Import data

In [19]:
import numpy as np
import pandas as pd
f500 = pd.read_csv("f500.csv")

In [20]:
# What is the type of f500 ?
type(f500)

pandas.core.frame.DataFrame

In [10]:
# What is the shape of f500 ?
f500.shape

(500, 16)

### Introducing dataframe

In [21]:
f500

,company,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
0,Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1,USA,"Bentonville, AR",http://www.walmart.com,23,2300000,77798
1,State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2,China,"Beijing, China",http://www.sgcc.com.cn,17,926067,209456
2,Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining,Energy,4,China,"Beijing, China",http://www.sinopec.com,19,713288,106523
3,China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3,China,"Beijing, China",http://www.cnpc.com.cn,17,1512048,301893
4,Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210
5,Volkswagen,6,240264,1.5,5937.3,432116,NaN,Matthias Muller,Motor Vehicles and Parts,Motor Vehicles & Parts,7,Germany,"Wolfsburg, Germany",http://www.volkswagen.com,23,626715,97753
6,Royal Dutch Shell,7,240033,-11.8,4575.0,411275,135.9,Ben van Beurden,Petroleum Refining,Energy,5,Netherlands,"The Hague, Netherlands",http://www.shell.com,23,89000,186646
7,Berkshire Hathaway,8,223604,6.1,24074.0,620854,NaN,Warren E. Buffett,Insurance: Property and Casualty (Stock),Financials,11,USA,"Omaha, NE",http://www.berkshirehathaway.com,21,367700,283001
8,Apple,9,215639,-7.7,45687.0,321686,-14.4,Timothy D. Cook,"Computers, Office Equipment",Technology,9,USA,"Cupertino, CA",http://www.apple.com,15,116000,128249
9,Exxon Mobil,10,205004,-16.7,7840.0,330314,-51.5,Darren W. Woods,Petroleum Refining,Energy,6,USA,"Irving, TX",http://www.exxonmobil.com,23,72700,167325
10,McKesson,11,198533,3.1,5070.0,60969,124.5,John H. Hammergren,Wholesalers: Health Care,Wholesalers,12,USA,"San Francisco, CA",http://www.mckesson.com,23,64500,11095
11,BP,12,186606,-17.4,115.0,263316,NaN,Robert W. Dudley,Petroleum Refining,Energy,10,Britain,"London, Britain",http://www.bp.com,23,74500,95286
12,UnitedHealth Group,13,184840,17.7,7017.0,122810,20.7,Stephen J. Hemsley,Health Care: Insurance and Managed Care,Health Care,17,USA,"Minnetonka, MN",http://www.unitedhealthgroup.com,21,230000,38274
13,CVS Health,14,177526,15.8,5317.0,94462,1.5,Larry J. Merlo,Health Care: Pharmacy and Other Services,Health Care,18,USA,"Woonsocket, RI",http://www.cvshealth.com,22,204000,36830
14,Samsung Electronics,15,173957,-2.0,19316.5,217104,16.8,Oh-Hyun Kwon,"Electronics, Electrical Equip.",Technology,13,South Korea,"Suwon, South Korea",http://www.samsung.com,23,325000,154376
15,Glencore,16,173883,2.0,1379.0,124600,NaN,Ivan Glasenberg,"Mining, Crude-Oil Production",Energy,14,Switzerland,"Baar, Switzerland",http://www.glencore.com,7,93123,44243
16,Daimler,17,169483,2.2,9428.4,256262,0.9,Dieter Zetsche,Motor Vehicles and Parts,Motor Vehicles & Parts,16,Germany,"Stuttgart, Germany",http://www.daimler.com,23,282488,61116
17,General Motors,18,166380,9.2,9427.0,221690,-2.7,Mary T. Barra,Motor Vehicles and Parts,Motor Vehicles & Parts,20,USA,"Detroit, MI",http://www.gm.com,23,225000,43836
18,AT&T,19,163786,11.6,12976.0,403821,-2.8,Randall L. Stephenson,Telecommunications,Telecommunications,23,USA,"Dallas, TX",http://www.att.com,23,268540,123135
19,EXOR Group,20,154894,1.5,651.3,186172,-21.1,John Elkann,Diversified Financials,Financials,19,Netherlands,"Amsterdam, Netherlands",http://www.exor.com,7,302562,11582
20,Ford Motor,21,151800,1.5,4596.0,237951,-37.7,James P. Hackett,Motor Vehicles and Parts,Motor Vehicles & Parts,21,USA,"Dearborn, MI",http://www.ford.com,23,201000,29170
21,Industrial & Commercial Bank of China,22,147675,-11.7,41883.9,3473238,-5.0,Gu Shu,Banks: Commercial and Savings,Financials,15,China,"Beijing, China",http://www.icbc-ltd.com,19,461749,283438
22,AmerisourceBergen,23,146850,8.0,1427.9,33656,NaN,Steven H. Collis,Wholesalers: Health Care,Wholesalers,28,USA,"Chesterbrook, PA",http://www.amerisourcebergen.com,18,18500,2129
23,China State Construction Engineering,24,144505,3.1,2492.9,201269,10.7,Guan Qing,"Engineering, Construction",Engineering & Construction,27,China,"Beijing, China",http://www.cscec.com,6,263915,15344
24,AXA,25,143722,11.2,6446.0,941556,3.5,Thomas Buberl,"Insurance: Life, Health (stock)",Financials,33,France,"Paris, France",http://www.axa.com,23,97707,74454
25,Amazon.com,26,135987,27.1,2371.0,83402,297.8,Jeffrey P. Bezos,Internet Services and Retailing,Technology,44,USA,"Seattle, WA",http://www.amazon.com,9,341400,19285
26,Hon Hai Precision Industry,27,135129,-4.3,4608.8,80436,-0.4,Terry Gou,"Electronics, Electrical Equip.",Technology,25,Taiwan,"New Taipei City, Taiwan",http://www.foxconn.com,13,726772,33476
27,China Construction Bank,28,135093,-8.7,34840.9,3016578,-4.0,Wang Hongzhang,Banks: Commercial and Savings,Financials,22,China,"Beijing, China",http://www.ccb.com,18,362482,226851
28,Honda Motor,29,129198,6.2,5690.3,170165,98.3,Takahiro Hachigo,Motor Vehicles and Parts,Motor Vehicles & Parts,36,Japan,"Tokyo, Japan",http://www.honda.com,23,211915,65482
29,Total,30,127925,-10.8,6196.0,230978,21.8,Patrick Pouyanne,Petroleum Refining,Energy,24,France,"Courbevoie, France",http://www.total.com,23,102168,98680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,Amgen,471,22991,6.1,7722.0,77626,11.3,Robert A. Bradway,Pharmaceuticals,Health Care,487,USA,"Thousand Oaks, CA",http://www.amgen.com,2,19200,29875
471,Rabobank Group,472,22956,-4.4,828.3,698790,-15.1,Wiebe Draijer,Banks: Commercial and Savings,Financials,445,Netherlands,"Utrecht, Netherlands",http://www.rabobank.com,23,40029,27232
472,Altice,473,22953,42.2,-1722.5,84805,NaN,Michel Combes,Telecommunications,Telecommunications,0,Netherlands,"Amsterdam, Netherlands",http://www.altice.net,1,49732,-2668
473,Onex,474,22943,3.8,-130.0,42913,NaN,Gerald W. Schwartz,Semiconductors and Other Electronic Components,Technology,483,Canada,"Toronto, Ontario, Canada",http://www.onex.com,18,161000,-490
474,US Foods Holding,475,22919,-0.9,209.8,8945,25.2,Pietro Satriano,Wholesalers: Food and Grocery,Wholesalers,461,USA,"Rosemont, IL",http://www.usfoods.com,2,25000,2538
475,Shanxi Jincheng Anthracite Coal Mining Group,476,22875,-17.0,3.0,32954,NaN,He Tiancai,"Mining, Crude-Oil Production",Energy,384,China,"Jincheng, China",http://www.jamg.cn,5,135691,2988
476,Randstad Holding,477,22873,7.3,650.2,9624,13.0,Jacques van den Broek,Temporary Help,Business Services,494,Netherlands,"Diemen, Netherlands",http://www.randstad.com,5,32280,4366
477,Tencent Holdings,478,22871,39.7,6185.9,56968,35.0,Pony Ma,Internet Services and Retailing,Technology,0,China,"Shenzhen, China",http://www.tencent.com,1,38775,25128
478,LG Display,479,22840,-9.0,781.4,20606,-8.6,Sang-Beom Han,"Electronics, Electrical Equip.",Technology,429,South Korea,"Seoul, South Korea",http://www.lgdisplay.com,6,49094,10729
479,Emirates Group,480,22799,0.3,340.3,33096,-82.5,Sheikh Ahmed bin Saeed Al Maktoum,Airlines,Transportation,472,U.A.E,"Dubai, U.A.E",http://www.theemiratesgroup.com,2,64768,9395
480,U.S. Bancorp,481,22744,5.8,5888.0,445964,0.2,Andrew J. Cecere,Banks: Commercial and Savings,Financials,490,USA,"Minneapolis, MN",http://www.usbank.com,12,71191,47298
481,H & M Hennes & Mauritz,482,22618,4.6,2192.3,10681,-12.3,Karl-Johan Persson,Specialty Retailers,Retailing,488,Sweden,"Stockholm, Sweden",http://www.hm.com,2,114586,6635
482,Aflac,483,22559,8.1,2659.0,129819,5.0,Daniel P. Amos,"Insurance: Life, Health (stock)",Financials,0,USA,"Columbus, GA",http://www.aflac.com,10,10212,20482
483,Sodexo,484,22477,-2.0,707.2,15766,-12.7,Michel Landel,Food Services,"Hotels, Restaurants & Leisure",466,France,"Issy-les-Moulineaux, France",http://www.sodexo.com,18,425594,4085
484,Suning Commerce Group,485,22366,3.7,106.0,19738,-23.6,Ren Jun,Specialty Retailers,Retailing,0,China,"Nanjing, China",http://www.suning.com,1,60354,9455
485,GS Caltex,486,22207,-11.4,1221.1,15969,42.1,Jin-Soo Huh,Petroleum Refining,Energy,431,South Korea,"Seoul, South Korea",http://www.gscaltex.com,6,2949,8150
486,Ultrapar Holdings,487,22167,-2.3,447.5,7426,-0.8,Thilo Mannhardt,Energy,Energy,474,Brazil,"Sao Paulo, Brazil",http://www.ultra.com.br,8,15173,2621
487,Xiamen C&D,488,22145,6.6,280.2,21729,15.6,Huang Wenzhou,Trading,Wholesalers,0,China,"Xiamen, China",http://www.chinacdc.com,1,18381,3985
488,Sears Holdings,489,22138,-12.0,-2221.0,9362,NaN,Edward S. Lampert,General Merchandisers,Retailing,425,USA,"Hoffman Estates, IL",http://www.searsholdings.com,23,140000,-3824
489,China General Technology,490,22113,-20.1,413.6,20860,-20.8,Xu Xianping,"Engineering, Construction",Engineering & Construction,383,China,"Beijing, China",http://www.genertec.com.cn,4,38589,5114
490,National Grid,491,22036,-3.2,10150.6,82310,160.2,John Pettigrew,Utilities,Energy,471,Britain,"London, Britain",http://www.nationalgrid.com,12,22132,25463
491,Dollar General,492,21987,7.9,1251.1,11672,7.4,Todd J. Vasos,Specialty Retailers,Retailing,0,USA,"Goodlettsville, TN",http://www.dollargeneral.com,1,121000,5406
492,Telecom Italia,493,21941,-17.4,1999.4,74295,NaN,Flavio Cattaneo,Telecommunications,Telecommunications,404,Italy,"Milan, Italy",http://www.telecomitalia.com,18,61227,22366
493,Xiamen ITG Holding Group,494,21930,34.3,35.6,12161,-25.1,Xu Xiaoxi,Trading,Wholesalers,0,China,"Xiamen, China",http://www.itgholding.com.cn,1,18454,1066
494,Xinjiang Guanghui Industry Investment,495,21919,31.1,251.8,31957,49.9,Shang Jiqiang,Trading,Wholesalers,0,China,"Urumqi, China",http://www.guanghui.com,1,65616,4563
495,Teva Pharmaceutical Industries,496,21903,11.5,329.0,92890,-79.3,Yitzhak Peterburg,Pharmaceuticals,Health Care,0,Israel,"Petach Tikva, Israel",http://www.tevapharm.com,1,56960,33337
496,New China Life Insurance,497,21796,-13.3,743.9,100609,-45.6,Wan Feng,"Insurance: Life, Health (stock)",Financials,427,China,"Beijing, China",http://www.newchinalife.com,2,54378,8507
497,Wm. Morrison Supermarkets,498,21741,-11.3,406.4,11630,20.4,David T. Potts,Food and Drug Stores,Food & Drug Stores,437,Britain,"Bradford, Britain",http://www.morrisons.com,13,77210,5111
498,TUI,499,21655,-5.5,1151.7,16247,195.5,Friedrich Joussen,Travel Services,Business Services,467,Germany,"Hanover, Germany",http://www.tuigroup.com,23,66779,3006
499,AutoNation,500,21609,3.6,430.5,10060,-2.7,Michael J. Jackson,Specialty Retailers,Retailing,0,USA,"Fort Lauderdale, FL",http://www.autonation.com,12,26000,2310

Dataframes are two dimensional pandas objects, the pandas equivalent of a Numpy 2D ndarray. Unlike NumPy, pandas does not use the same type for 1D and 2D arrays.

In [13]:
# Get information about the types of each column
f500.dtypes

rank                          int64
revenues                      int64
revenue_change              float64
profits                     float64
assets                        int64
profit_change               float64
ceo                          object
industry                     object
sector                       object
previous_rank                 int64
country                      object
hq_location                  object
website                      object
years_on_global_500_list      int64
employees                     int64
total_stockholder_equity      int64
dtype: object

In [14]:
# Get the first few rows
f500.head()

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
company,,,,,,,,,,,,,,,,
Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1,USA,"Bentonville, AR",http://www.walmart.com,23,2300000,77798
State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2,China,"Beijing, China",http://www.sgcc.com.cn,17,926067,209456
Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining,Energy,4,China,"Beijing, China",http://www.sinopec.com,19,713288,106523
China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3,China,"Beijing, China",http://www.cnpc.com.cn,17,1512048,301893
Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210

In [15]:
# Get the last few rows
f500.tail()

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
company,,,,,,,,,,,,,,,,
Teva Pharmaceutical Industries,496,21903,11.5,329.0,92890,-79.3,Yitzhak Peterburg,Pharmaceuticals,Health Care,0,Israel,"Petach Tikva, Israel",http://www.tevapharm.com,1,56960,33337
New China Life Insurance,497,21796,-13.3,743.9,100609,-45.6,Wan Feng,"Insurance: Life, Health (stock)",Financials,427,China,"Beijing, China",http://www.newchinalife.com,2,54378,8507
Wm. Morrison Supermarkets,498,21741,-11.3,406.4,11630,20.4,David T. Potts,Food and Drug Stores,Food & Drug Stores,437,Britain,"Bradford, Britain",http://www.morrisons.com,13,77210,5111
TUI,499,21655,-5.5,1151.7,16247,195.5,Friedrich Joussen,Travel Services,Business Services,467,Germany,"Hanover, Germany",http://www.tuigroup.com,23,66779,3006
AutoNation,500,21609,3.6,430.5,10060,-2.7,Michael J. Jackson,Specialty Retailers,Retailing,0,USA,"Fort Lauderdale, FL",http://www.autonation.com,12,26000,2310

In [16]:
# Overview 
f500.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
rank                        500 non-null int64
revenues                    500 non-null int64
revenue_change              498 non-null float64
profits                     499 non-null float64
assets                      500 non-null int64
profit_change               436 non-null float64
ceo                         500 non-null object
industry                    500 non-null object
sector                      500 non-null object
previous_rank               500 non-null int64
country                     500 non-null object
hq_location                 500 non-null object
website                     500 non-null object
years_on_global_500_list    500 non-null int64
employees                   500 non-null int64
total_stockholder_equity    500 non-null int64
dtypes: float64(3), int64(7), object(6)
memory usage: 66.4+ KB

### Selecting columns from a dataframe by label

Because our axes in pandas have labels, we can select data using those labels, unlike in NumPy where we needed to know the exact index location. To do this, we use the DataFrame.loc[] method.

In [17]:
# Select a single column by specifying a single label
f500.loc[:, 'rank']

company
Walmart                                           1
State Grid                                        2
Sinopec Group                                     3
China National Petroleum                          4
Toyota Motor                                      5
Volkswagen                                        6
Royal Dutch Shell                                 7
Berkshire Hathaway                                8
Apple                                             9
Exxon Mobil                                      10
McKesson                                         11
BP                                               12
UnitedHealth Group                               13
CVS Health                                       14
Samsung Electronics                              15
Glencore                                         16
Daimler                                          17
General Motors                                   18
AT&T                                             19
EXOR Group                                       20
Ford Motor                                       21
Industrial & Commercial Bank of China            22
AmerisourceBergen                                23
China State Construction Engineering             24
AXA                                              25
Amazon.com                                       26
Hon Hai Precision Industry                       27
China Construction Bank                          28
Honda Motor                                      29
Total                                            30
                                               ...
Amgen                                           471
Rabobank Group                                  472
Altice                                          473
Onex                                            474
US Foods Holding                                475
Shanxi Jincheng Anthracite Coal Mining Group    476
Randstad Holding                                477
Tencent Holdings                                478
LG Display                                      479
Emirates Group                                  480
U.S. Bancorp                                    481
H & M Hennes & Mauritz                          482
Aflac                                           483
Sodexo                                          484
Suning Commerce Group                           485
GS Caltex                                       486
Ultrapar Holdings                               487
Xiamen C&D                                      488
Sears Holdings                                  489
China General Technology                        490
National Grid                                   491
Dollar General                                  492
Telecom Italia                                  493
Xiamen ITG Holding Group                        494
Xinjiang Guanghui Industry Investment           495
Teva Pharmaceutical Industries                  496
New China Life Insurance                        497
Wm. Morrison Supermarkets                       498
TUI                                             499
AutoNation                                      500
Name: rank, Length: 500, dtype: int64

We see that selecting a single column returns a pandas series. We'll talk about pandas series later in this notebook, but for now the important thing is to note that the new series has the same index axis labels as the original dataframe.

In [18]:
# Select multiple columns using a list of labels
f500.loc[:, ['rank', 'country']]

                                              rank      country
company
Walmart                                          1          USA
State Grid                                       2        China
Sinopec Group                                    3        China
China National Petroleum                         4        China
Toyota Motor                                     5        Japan
Volkswagen                                       6      Germany
Royal Dutch Shell                                7  Netherlands
Berkshire Hathaway                               8          USA
Apple                                            9          USA
Exxon Mobil                                     10          USA
McKesson                                        11          USA
BP                                              12      Britain
UnitedHealth Group                              13          USA
CVS Health                                      14          USA
Samsung Electronics                             15  South Korea
Glencore                                        16  Switzerland
Daimler                                         17      Germany
General Motors                                  18          USA
AT&T                                            19          USA
EXOR Group                                      20  Netherlands
Ford Motor                                      21          USA
Industrial & Commercial Bank of China           22        China
AmerisourceBergen                               23          USA
China State Construction Engineering            24        China
AXA                                             25       France
Amazon.com                                      26          USA
Hon Hai Precision Industry                      27       Taiwan
China Construction Bank                         28        China
Honda Motor                                     29        Japan
Total                                           30       France
...                                            ...          ...
Amgen                                          471          USA
Rabobank Group                                 472  Netherlands
Altice                                         473  Netherlands
Onex                                           474       Canada
US Foods Holding                               475          USA
Shanxi Jincheng Anthracite Coal Mining Group   476        China
Randstad Holding                               477  Netherlands
Tencent Holdings                               478        China
LG Display                                     479  South Korea
Emirates Group                                 480        U.A.E
U.S. Bancorp                                   481          USA
H & M Hennes & Mauritz                         482       Sweden
Aflac                                          483          USA
Sodexo                                         484       France
Suning Commerce Group                          485        China
GS Caltex                                      486  South Korea
Ultrapar Holdings                              487       Brazil
Xiamen C&D                                     488        China
Sears Holdings                                 489          USA
China General Technology                       490        China
National Grid                                  491      Britain
Dollar General                                 492          USA
Telecom Italia                                 493        Italy
Xiamen ITG Holding Group                       494        China
Xinjiang Guanghui Industry Investment          495        China
Teva Pharmaceutical Industries                 496       Israel
New China Life Insurance                       497        China
Wm. Morrison Supermarkets                      498      Britain
TUI                                            499      Germany
AutoNation                                     500          USA

[500 rows x 2 columns]

When we use a list of labels, a dataframe is returned with only the columns specified in our list, in the order specified in our list. Just like when we used a single column label, the new dataframe has the same index axis labels as the original.

In [19]:
# Select multiple columns using slicing
f500.loc[:, 'rank':'industry']

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry
company,,,,,,,,
Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers
State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities
Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining
China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining
Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts
Volkswagen,6,240264,1.5,5937.3,432116,NaN,Matthias Muller,Motor Vehicles and Parts
Royal Dutch Shell,7,240033,-11.8,4575.0,411275,135.9,Ben van Beurden,Petroleum Refining
Berkshire Hathaway,8,223604,6.1,24074.0,620854,NaN,Warren E. Buffett,Insurance: Property and Casualty (Stock)
Apple,9,215639,-7.7,45687.0,321686,-14.4,Timothy D. Cook,"Computers, Office Equipment"
Exxon Mobil,10,205004,-16.7,7840.0,330314,-51.5,Darren W. Woods,Petroleum Refining
McKesson,11,198533,3.1,5070.0,60969,124.5,John H. Hammergren,Wholesalers: Health Care
BP,12,186606,-17.4,115.0,263316,NaN,Robert W. Dudley,Petroleum Refining
UnitedHealth Group,13,184840,17.7,7017.0,122810,20.7,Stephen J. Hemsley,Health Care: Insurance and Managed Care
CVS Health,14,177526,15.8,5317.0,94462,1.5,Larry J. Merlo,Health Care: Pharmacy and Other Services
Samsung Electronics,15,173957,-2.0,19316.5,217104,16.8,Oh-Hyun Kwon,"Electronics, Electrical Equip."
Glencore,16,173883,2.0,1379.0,124600,NaN,Ivan Glasenberg,"Mining, Crude-Oil Production"
Daimler,17,169483,2.2,9428.4,256262,0.9,Dieter Zetsche,Motor Vehicles and Parts
General Motors,18,166380,9.2,9427.0,221690,-2.7,Mary T. Barra,Motor Vehicles and Parts
AT&T,19,163786,11.6,12976.0,403821,-2.8,Randall L. Stephenson,Telecommunications
EXOR Group,20,154894,1.5,651.3,186172,-21.1,John Elkann,Diversified Financials
Ford Motor,21,151800,1.5,4596.0,237951,-37.7,James P. Hackett,Motor Vehicles and Parts
Industrial & Commercial Bank of China,22,147675,-11.7,41883.9,3473238,-5.0,Gu Shu,Banks: Commercial and Savings
AmerisourceBergen,23,146850,8.0,1427.9,33656,NaN,Steven H. Collis,Wholesalers: Health Care
China State Construction Engineering,24,144505,3.1,2492.9,201269,10.7,Guan Qing,"Engineering, Construction"
AXA,25,143722,11.2,6446.0,941556,3.5,Thomas Buberl,"Insurance: Life, Health (stock)"
Amazon.com,26,135987,27.1,2371.0,83402,297.8,Jeffrey P. Bezos,Internet Services and Retailing
Hon Hai Precision Industry,27,135129,-4.3,4608.8,80436,-0.4,Terry Gou,"Electronics, Electrical Equip."
China Construction Bank,28,135093,-8.7,34840.9,3016578,-4.0,Wang Hongzhang,Banks: Commercial and Savings
Honda Motor,29,129198,6.2,5690.3,170165,98.3,Takahiro Hachigo,Motor Vehicles and Parts
Total,30,127925,-10.8,6196.0,230978,21.8,Patrick Pouyanne,Petroleum Refining
...,...,...,...,...,...,...,...,...
Amgen,471,22991,6.1,7722.0,77626,11.3,Robert A. Bradway,Pharmaceuticals
Rabobank Group,472,22956,-4.4,828.3,698790,-15.1,Wiebe Draijer,Banks: Commercial and Savings
Altice,473,22953,42.2,-1722.5,84805,NaN,Michel Combes,Telecommunications
Onex,474,22943,3.8,-130.0,42913,NaN,Gerald W. Schwartz,Semiconductors and Other Electronic Components
US Foods Holding,475,22919,-0.9,209.8,8945,25.2,Pietro Satriano,Wholesalers: Food and Grocery
Shanxi Jincheng Anthracite Coal Mining Group,476,22875,-17.0,3.0,32954,NaN,He Tiancai,"Mining, Crude-Oil Production"
Randstad Holding,477,22873,7.3,650.2,9624,13.0,Jacques van den Broek,Temporary Help
Tencent Holdings,478,22871,39.7,6185.9,56968,35.0,Pony Ma,Internet Services and Retailing
LG Display,479,22840,-9.0,781.4,20606,-8.6,Sang-Beom Han,"Electronics, Electrical Equip."
Emirates Group,480,22799,0.3,340.3,33096,-82.5,Sheikh Ahmed bin Saeed Al Maktoum,Airlines
U.S. Bancorp,481,22744,5.8,5888.0,445964,0.2,Andrew J. Cecere,Banks: Commercial and Savings
H & M Hennes & Mauritz,482,22618,4.6,2192.3,10681,-12.3,Karl-Johan Persson,Specialty Retailers
Aflac,483,22559,8.1,2659.0,129819,5.0,Daniel P. Amos,"Insurance: Life, Health (stock)"
Sodexo,484,22477,-2.0,707.2,15766,-12.7,Michel Landel,Food Services
Suning Commerce Group,485,22366,3.7,106.0,19738,-23.6,Ren Jun,Specialty Retailers
GS Caltex,486,22207,-11.4,1221.1,15969,42.1,Jin-Soo Huh,Petroleum Refining
Ultrapar Holdings,487,22167,-2.3,447.5,7426,-0.8,Thilo Mannhardt,Energy
Xiamen C&D,488,22145,6.6,280.2,21729,15.6,Huang Wenzhou,Trading
Sears Holdings,489,22138,-12.0,-2221.0,9362,NaN,Edward S. Lampert,General Merchandisers
China General Technology,490,22113,-20.1,413.6,20860,-20.8,Xu Xianping,"Engineering, Construction"
National Grid,491,22036,-3.2,10150.6,82310,160.2,John Pettigrew,Utilities
Dollar General,492,21987,7.9,1251.1,11672,7.4,Todd J. Vasos,Specialty Retailers
Telecom Italia,493,21941,-17.4,1999.4,74295,NaN,Flavio Cattaneo,Telecommunications
Xiamen ITG Holding Group,494,21930,34.3,35.6,12161,-25.1,Xu Xiaoxi,Trading
Xinjiang Guanghui Industry Investment,495,21919,31.1,251.8,31957,49.9,Shang Jiqiang,Trading
Teva Pharmaceutical Industries,496,21903,11.5,329.0,92890,-79.3,Yitzhak Peterburg,Pharmaceuticals
New China Life Insurance,497,21796,-13.3,743.9,100609,-45.6,Wan Feng,"Insurance: Life, Health (stock)"
Wm. Morrison Supermarkets,498,21741,-11.3,406.4,11630,20.4,David T. Potts,Food and Drug Stores
TUI,499,21655,-5.5,1151.7,16247,195.5,Friedrich Joussen,Travel Services
AutoNation,500,21609,3.6,430.5,10060,-2.7,Michael J. Jackson,Specialty Retailers

### Two simpler ways to select columns

In [20]:
# 1. Single bracket
f500['country']

company
Walmart                                                 USA
State Grid                                            China
Sinopec Group                                         China
China National Petroleum                              China
Toyota Motor                                          Japan
Volkswagen                                          Germany
Royal Dutch Shell                               Netherlands
Berkshire Hathaway                                      USA
Apple                                                   USA
Exxon Mobil                                             USA
McKesson                                                USA
BP                                                  Britain
UnitedHealth Group                                      USA
CVS Health                                              USA
Samsung Electronics                             South Korea
Glencore                                        Switzerland
Daimler                                             Germany
General Motors                                          USA
AT&T                                                    USA
EXOR Group                                      Netherlands
Ford Motor                                              USA
Industrial & Commercial Bank of China                 China
AmerisourceBergen                                       USA
China State Construction Engineering                  China
AXA                                                  France
Amazon.com                                              USA
Hon Hai Precision Industry                           Taiwan
China Construction Bank                               China
Honda Motor                                           Japan
Total                                                France
                                                   ...
Amgen                                                   USA
Rabobank Group                                  Netherlands
Altice                                          Netherlands
Onex                                                 Canada
US Foods Holding                                        USA
Shanxi Jincheng Anthracite Coal Mining Group          China
Randstad Holding                                Netherlands
Tencent Holdings                                      China
LG Display                                      South Korea
Emirates Group                                        U.A.E
U.S. Bancorp                                            USA
H & M Hennes & Mauritz                               Sweden
Aflac                                                   USA
Sodexo                                               France
Suning Commerce Group                                 China
GS Caltex                                       South Korea
Ultrapar Holdings                                    Brazil
Xiamen C&D                                            China
Sears Holdings                                          USA
China General Technology                              China
National Grid                                       Britain
Dollar General                                          USA
Telecom Italia                                        Italy
Xiamen ITG Holding Group                              China
Xinjiang Guanghui Industry Investment                 China
Teva Pharmaceutical Industries                       Israel
New China Life Insurance                              China
Wm. Morrison Supermarkets                           Britain
TUI                                                 Germany
AutoNation                                              USA
Name: country, Length: 500, dtype: object

In [23]:
f500[['rank','country']]

                                              rank      country
company
Walmart                                          1          USA
State Grid                                       2        China
Sinopec Group                                    3        China
China National Petroleum                         4        China
Toyota Motor                                     5        Japan
Volkswagen                                       6      Germany
Royal Dutch Shell                                7  Netherlands
Berkshire Hathaway                               8          USA
Apple                                            9          USA
Exxon Mobil                                     10          USA
McKesson                                        11          USA
BP                                              12      Britain
UnitedHealth Group                              13          USA
CVS Health                                      14          USA
Samsung Electronics                             15  South Korea
Glencore                                        16  Switzerland
Daimler                                         17      Germany
General Motors                                  18          USA
AT&T                                            19          USA
EXOR Group                                      20  Netherlands
Ford Motor                                      21          USA
Industrial & Commercial Bank of China           22        China
AmerisourceBergen                               23          USA
China State Construction Engineering            24        China
AXA                                             25       France
Amazon.com                                      26          USA
Hon Hai Precision Industry                      27       Taiwan
China Construction Bank                         28        China
Honda Motor                                     29        Japan
Total                                           30       France
...                                            ...          ...
Amgen                                          471          USA
Rabobank Group                                 472  Netherlands
Altice                                         473  Netherlands
Onex                                           474       Canada
US Foods Holding                               475          USA
Shanxi Jincheng Anthracite Coal Mining Group   476        China
Randstad Holding                               477  Netherlands
Tencent Holdings                               478        China
LG Display                                     479  South Korea
Emirates Group                                 480        U.A.E
U.S. Bancorp                                   481          USA
H & M Hennes & Mauritz                         482       Sweden
Aflac                                          483          USA
Sodexo                                         484       France
Suning Commerce Group                          485        China
GS Caltex                                      486  South Korea
Ultrapar Holdings                              487       Brazil
Xiamen C&D                                     488        China
Sears Holdings                                 489          USA
China General Technology                       490        China
National Grid                                  491      Britain
Dollar General                                 492          USA
Telecom Italia                                 493        Italy
Xiamen ITG Holding Group                       494        China
Xinjiang Guanghui Industry Investment          495        China
Teva Pharmaceutical Industries                 496       Israel
New China Life Insurance                       497        China
Wm. Morrison Supermarkets                      498      Britain
TUI                                            499      Germany
AutoNation                                     500          USA

[500 rows x 2 columns]

In [24]:
# 2. Dot Accessor
f500.ceo

company
Walmart                                                       C. Douglas McMillon
State Grid                                                                Kou Wei
Sinopec Group                                                           Wang Yupu
China National Petroleum                                            Zhang Jianhua
Toyota Motor                                                          Akio Toyoda
Volkswagen                                                        Matthias Muller
Royal Dutch Shell                                                 Ben van Beurden
Berkshire Hathaway                                              Warren E. Buffett
Apple                                                             Timothy D. Cook
Exxon Mobil                                                       Darren W. Woods
McKesson                                                       John H. Hammergren
BP                                                               Robert W. Dudley
UnitedHealth Group                                             Stephen J. Hemsley
CVS Health                                                         Larry J. Merlo
Samsung Electronics                                                  Oh-Hyun Kwon
Glencore                                                          Ivan Glasenberg
Daimler                                                            Dieter Zetsche
General Motors                                                      Mary T. Barra
AT&T                                                        Randall L. Stephenson
EXOR Group                                                            John Elkann
Ford Motor                                                       James P. Hackett
Industrial & Commercial Bank of China                                      Gu Shu
AmerisourceBergen                                                Steven H. Collis
China State Construction Engineering                                    Guan Qing
AXA                                                                 Thomas Buberl
Amazon.com                                                       Jeffrey P. Bezos
Hon Hai Precision Industry                                              Terry Gou
China Construction Bank                                            Wang Hongzhang
Honda Motor                                                      Takahiro Hachigo
Total                                                            Patrick Pouyanne
                                                              ...
Amgen                                                           Robert A. Bradway
Rabobank Group                                                      Wiebe Draijer
Altice                                                              Michel Combes
Onex                                                           Gerald W. Schwartz
US Foods Holding                                                  Pietro Satriano
Shanxi Jincheng Anthracite Coal Mining Group                           He Tiancai
Randstad Holding                                            Jacques van den Broek
Tencent Holdings                                                          Pony Ma
LG Display                                                          Sang-Beom Han
Emirates Group                                  Sheikh Ahmed bin Saeed Al Maktoum
U.S. Bancorp                                                     Andrew J. Cecere
H & M Hennes & Mauritz                                         Karl-Johan Persson
Aflac                                                              Daniel P. Amos
Sodexo                                                              Michel Landel
Suning Commerce Group                                                     Ren Jun
GS Caltex                                                             Jin-Soo Huh
Ultrapar Holdings                                                 Thilo Mannhardt
Xiamen C&D                                                          Huang Wenzhou
Sears Holdings                                                  Edward S. Lampert
China General Technology                                              Xu Xianping
National Grid                                                      John Pettigrew
Dollar General                                                      Todd J. Vasos
Telecom Italia                                                    Flavio Cattaneo
Xiamen ITG Holding Group                                                Xu Xiaoxi
Xinjiang Guanghui Industry Investment                               Shang Jiqiang
Teva Pharmaceutical Industries                                  Yitzhak Peterburg
New China Life Insurance                                                 Wan Feng
Wm. Morrison Supermarkets                                          David T. Potts
TUI                                                             Friedrich Joussen
AutoNation                                                     Michael J. Jackson
Name: ceo, Length: 500, dtype: object

### Selecting Items from a Series by Label

Series is the pandas type for one-dimensional objects. Anytime you see a 1D pandas object, it will be a series, and anytime you see a 2D pandas object, it will be a dataframe.

In [27]:
ceos = f500['ceo']

In [28]:
type(ceos)

pandas.core.series.Series

Just like dataframes, we can use Series.loc[] to select items from a series using single labels, a list, or a slice object. We can also omit loc[] and use bracket shortcuts for all three.

In [40]:
# Using .loc with a single label
ceos.loc['Facebook']

'Mark Zuckerberg'

In [41]:
# Using .loc with a list
ceos.loc[['Berkshire Hathaway', 'Amazon.com']]

company
Berkshire Hathaway    Warren E. Buffett
Amazon.com             Jeffrey P. Bezos
Name: ceo, dtype: object

In [35]:
# Using .loc with a slice
ceos.loc['Walmart':'Apple']

company
Walmart                     C. Douglas McMillon
State Grid                              Kou Wei
Sinopec Group                         Wang Yupu
China National Petroleum          Zhang Jianhua
Toyota Motor                        Akio Toyoda
Volkswagen                      Matthias Muller
Royal Dutch Shell               Ben van Beurden
Berkshire Hathaway            Warren E. Buffett
Apple                           Timothy D. Cook
Name: ceo, dtype: object

### Selecting Rows From a Dataframe by Label

In [44]:
# Select a single row
f500.country.head(100)

company
Walmart                                          USA
State Grid                                     China
Sinopec Group                                  China
China National Petroleum                       China
Toyota Motor                                   Japan
Volkswagen                                   Germany
Royal Dutch Shell                        Netherlands
Berkshire Hathaway                               USA
Apple                                            USA
Exxon Mobil                                      USA
McKesson                                         USA
BP                                           Britain
UnitedHealth Group                               USA
CVS Health                                       USA
Samsung Electronics                      South Korea
Glencore                                 Switzerland
Daimler                                      Germany
General Motors                                   USA
AT&T                                             USA
EXOR Group                               Netherlands
Ford Motor                                       USA
Industrial & Commercial Bank of China          China
AmerisourceBergen                                USA
China State Construction Engineering           China
AXA                                           France
Amazon.com                                       USA
Hon Hai Precision Industry                    Taiwan
China Construction Bank                        China
Honda Motor                                    Japan
Total                                         France
                                            ...
Hitachi                                        Japan
SoftBank Group                                 Japan
Banco Santander                                Spain
Citigroup                                        USA
Petrobras                                     Brazil
Robert Bosch                                 Germany
Deutsche Telekom                             Germany
Hyundai Motor                            South Korea
Comcast                                          USA
Credit Agricole                               France
IBM                                              USA
Electricite de France                         France
Huawei Investment & Holding                    China
Enel                                           Italy
State Farm Insurance Cos.                        USA
China Resources National                       China
AEON                                           Japan
HSBC Holdings                                Britain
Pacific Construction Group                     China
Aviva                                        Britain
Uniper                                       Germany
Tesco                                        Britain
Engie                                         France
Airbus Group                             Netherlands
SK Holdings                              South Korea
Phillips 66                                      USA
Johnson & Johnson                                USA
Procter & Gamble                                 USA
U.S. Postal Service                              USA
China Southern Power Grid                      China
Name: country, Length: 100, dtype: object

In [52]:
# Select a list of row
f500.loc[['Alphabet', 'Toyota Motor']]

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
company,,,,,,,,,,,,,,,,
Alphabet,65,90272,20.4,19478.0,167497,19.1,Larry Page,Internet Services and Retailing,Technology,94,USA,"Mountain View, CA",http://www.abc.xyz,9,72053,139036
Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210

In [68]:
# Select mulitple rows using slicing
f500.loc['Samsung Electronics':'AT&T']

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
company,,,,,,,,,,,,,,,,
Samsung Electronics,15,173957,-2.0,19316.5,217104,16.8,Oh-Hyun Kwon,"Electronics, Electrical Equip.",Technology,13,South Korea,"Suwon, South Korea",http://www.samsung.com,23,325000,154376
Glencore,16,173883,2.0,1379.0,124600,NaN,Ivan Glasenberg,"Mining, Crude-Oil Production",Energy,14,Switzerland,"Baar, Switzerland",http://www.glencore.com,7,93123,44243
Daimler,17,169483,2.2,9428.4,256262,0.9,Dieter Zetsche,Motor Vehicles and Parts,Motor Vehicles & Parts,16,Germany,"Stuttgart, Germany",http://www.daimler.com,23,282488,61116
General Motors,18,166380,9.2,9427.0,221690,-2.7,Mary T. Barra,Motor Vehicles and Parts,Motor Vehicles & Parts,20,USA,"Detroit, MI",http://www.gm.com,23,225000,43836
AT&T,19,163786,11.6,12976.0,403821,-2.8,Randall L. Stephenson,Telecommunications,Telecommunications,23,USA,"Dallas, TX",http://www.att.com,23,268540,123135

### Series and Dataframe Describe Methods

In [75]:
# Describe the dataframe, show only numeric comlumns
f500.describe()

,rank,revenues,revenue_change,profits,assets,profit_change,previous_rank,years_on_global_500_list,employees,total_stockholder_equity
count,500.000000,500.000000,498.000000,499.000000,5.000000e+02,436.000000,500.000000,500.000000,5.000000e+02,500.000000
mean,250.500000,55416.358000,4.538353,3055.203206,2.436323e+05,24.152752,222.134000,15.036000,1.339983e+05,30628.076000
std,144.481833,45725.478963,28.549067,5171.981071,4.851937e+05,437.509566,146.941961,7.932752,1.700878e+05,43642.576833
min,1.000000,21609.000000,-67.300000,-13038.000000,3.717000e+03,-793.700000,0.000000,1.000000,3.280000e+02,-59909.000000
25%,125.750000,29003.000000,-5.900000,556.950000,3.658850e+04,-22.775000,92.750000,7.000000,4.293250e+04,7553.750000
50%,250.500000,40236.000000,0.550000,1761.600000,7.326150e+04,-0.350000,219.500000,17.000000,9.291050e+04,15809.500000
75%,375.250000,63926.750000,6.975000,3954.000000,1.805640e+05,17.700000,347.250000,23.000000,1.689172e+05,37828.500000
max,500.000000,485873.000000,442.300000,45687.000000,3.473238e+06,8909.500000,500.000000,23.000000,2.300000e+06,301893.000000

In [77]:
# Describe the dataframe, show only non-numeric comlumns
f500.describe(include=['O'])

,ceo,industry,sector,country,hq_location,website
count,500,500,500,500,500,500
unique,500,58,21,34,235,500
top,William J. DeLaney III,Banks: Commercial and Savings,Financials,USA,"Beijing, China",http://www.sinochem.com
freq,1,51,118,132,56,1

In [73]:
# Describe a Numeric Serie
f500['profits'].describe()

count      499.000000
mean      3055.203206
std       5171.981071
min     -13038.000000
25%        556.950000
50%       1761.600000
75%       3954.000000
max      45687.000000
Name: profits, dtype: float64

In [74]:
# Describe a String Serie
f500['country'].describe()

count     500
unique     34
top       USA
freq      132
Name: country, dtype: object

### Some Aggregrate Functions

In [81]:
# Top 10 countries
f500['country'].value_counts().head(10)

USA            132
China          109
Japan           51
Germany         29
France          29
Britain         24
South Korea     15
Switzerland     14
Netherlands     14
Canada          11
Name: country, dtype: int64

In [106]:
# Maximum profit
profits = f500['profits']
profits.max()

45687.0

In [110]:
# Which company has the maximum profit
profits.idxmax()

'Apple'

In [113]:
# Sum of all revenues
f500['revenues'].sum()

27708179

### Assignment with pandas

When we used NumPy, we learned that the same techniques that we use to select data could be used for assignment.

In [158]:
# Setting a value
f500.loc['Facebook', 'ceo'] = 'Pandas'

In [160]:
f500.ceo.Facebook

'Pandas'

In [162]:
# Add a new column
f500['revenues_b'] = f500['revenues'] / 1000

In [163]:
f500.head()

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity,revenues_b
company,,,,,,,,,,,,,,,,,
Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1,USA,"Bentonville, AR",http://www.walmart.com,23,2300000,77798,485.873
State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2,China,"Beijing, China",http://www.sgcc.com.cn,17,926067,209456,315.199
Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining,Energy,4,China,"Beijing, China",http://www.sinopec.com,19,713288,106523,267.518
China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3,China,"Beijing, China",http://www.cnpc.com.cn,17,1512048,301893,262.573
Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210,254.694

### Using Boolean Indexing with pandas Objects

Just like NumPy, pandas allows us to use boolean indexing to select items based on their value

In [188]:
# Get a boolean Series, Is a country in South Korea ?
in_korea = (f500['country'] == 'South Korea')

In [189]:
in_korea

company
Walmart                                         False
State Grid                                      False
Sinopec Group                                   False
China National Petroleum                        False
Toyota Motor                                    False
Volkswagen                                      False
Royal Dutch Shell                               False
Berkshire Hathaway                              False
Apple                                           False
Exxon Mobil                                     False
McKesson                                        False
BP                                              False
UnitedHealth Group                              False
CVS Health                                      False
Samsung Electronics                              True
Glencore                                        False
Daimler                                         False
General Motors                                  False
AT&T                                            False
EXOR Group                                      False
Ford Motor                                      False
Industrial & Commercial Bank of China           False
AmerisourceBergen                               False
China State Construction Engineering            False
AXA                                             False
Amazon.com                                      False
Hon Hai Precision Industry                      False
China Construction Bank                         False
Honda Motor                                     False
Total                                           False
                                                ...
Amgen                                           False
Rabobank Group                                  False
Altice                                          False
Onex                                            False
US Foods Holding                                False
Shanxi Jincheng Anthracite Coal Mining Group    False
Randstad Holding                                False
Tencent Holdings                                False
LG Display                                       True
Emirates Group                                  False
U.S. Bancorp                                    False
H & M Hennes & Mauritz                          False
Aflac                                           False
Sodexo                                          False
Suning Commerce Group                           False
GS Caltex                                        True
Ultrapar Holdings                               False
Xiamen C&D                                      False
Sears Holdings                                  False
China General Technology                        False
National Grid                                   False
Dollar General                                  False
Telecom Italia                                  False
Xiamen ITG Holding Group                        False
Xinjiang Guanghui Industry Investment           False
Teva Pharmaceutical Industries                  False
New China Life Insurance                        False
Wm. Morrison Supermarkets                       False
TUI                                             False
AutoNation                                      False
Name: country, Length: 500, dtype: bool

In [230]:
# Get countries in South Korea 
f500[in_korea].head()

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity,revenues_b
company,,,,,,,,,,,,,,,,,
Samsung Electronics,15.0,173957.0,-2.0,19316.5,217104.0,16.8,Oh-Hyun Kwon,"Electronics, Electrical Equip.",Technology,13.0,South Korea,"Suwon, South Korea",http://www.samsung.com,23.0,325000.0,154376.0,173.957
Hyundai Motor,78.0,80701.0,-0.8,4659.0,148092.0,-17.9,Mong-Koo Chung,Motor Vehicles and Parts,Motor Vehicles & Parts,84.0,South Korea,"Seoul, South Korea",http://worldwide.hyundai.com,22.0,129315.0,55639.0,80.701
SK Holdings,95.0,72579.0,107.4,659.7,85332.0,-86.0,Tae Won Chey,Petroleum Refining,Energy,294.0,South Korea,"Seoul, South Korea",http://www.sk.co.kr,2.0,84000.0,10858.0,72.579
Korea Electric Power,177.0,51500.0,-0.6,6074.1,147265.0,-48.3,Hwan-Eik Cho,Utilities,Energy,172.0,South Korea,"Jeollanam-do, South Korea",http://www.kepco.co.kr,23.0,43688.0,59394.0,51.500
LG Electronics,201.0,47712.0,-4.6,66.2,31348.0,-39.8,Seong-Jin Jo,"Electronics, Electrical Equip.",Technology,180.0,South Korea,"Seoul, South Korea",http://www.lg.com,17.0,75000.0,9926.0,47.712

### Using Boolean Arrays to Assign Values

In [200]:
f500[['rank','previous_rank']].head()

                          rank  previous_rank
company
Walmart                      1              1
State Grid                   2              2
Sinopec Group                3              4
China National Petroleum     4              3
Toyota Motor                 5              8

In [203]:
f500['previous_rank'].value_counts().head()

0      33
159     1
147     1
148     1
149     1
Name: previous_rank, dtype: int64

In [204]:
f500['previous_rank'] == 0

company
Walmart                                         False
State Grid                                      False
Sinopec Group                                   False
China National Petroleum                        False
Toyota Motor                                    False
Volkswagen                                      False
Royal Dutch Shell                               False
Berkshire Hathaway                              False
Apple                                           False
Exxon Mobil                                     False
McKesson                                        False
BP                                              False
UnitedHealth Group                              False
CVS Health                                      False
Samsung Electronics                             False
Glencore                                        False
Daimler                                         False
General Motors                                  False
AT&T                                            False
EXOR Group                                      False
Ford Motor                                      False
Industrial & Commercial Bank of China           False
AmerisourceBergen                               False
China State Construction Engineering            False
AXA                                             False
Amazon.com                                      False
Hon Hai Precision Industry                      False
China Construction Bank                         False
Honda Motor                                     False
Total                                           False
                                                ...
Amgen                                           False
Rabobank Group                                  False
Altice                                           True
Onex                                            False
US Foods Holding                                False
Shanxi Jincheng Anthracite Coal Mining Group    False
Randstad Holding                                False
Tencent Holdings                                 True
LG Display                                      False
Emirates Group                                  False
U.S. Bancorp                                    False
H & M Hennes & Mauritz                          False
Aflac                                            True
Sodexo                                          False
Suning Commerce Group                            True
GS Caltex                                       False
Ultrapar Holdings                               False
Xiamen C&D                                       True
Sears Holdings                                  False
China General Technology                        False
National Grid                                   False
Dollar General                                   True
Telecom Italia                                  False
Xiamen ITG Holding Group                         True
Xinjiang Guanghui Industry Investment            True
Teva Pharmaceutical Industries                   True
New China Life Insurance                        False
Wm. Morrison Supermarkets                       False
TUI                                             False
AutoNation                                       True
Name: previous_rank, Length: 500, dtype: bool

In [207]:
f500[f500['previous_rank'] == 0] = np.nan

In [208]:
f500['previous_rank'].value_counts().head()

471.0    1
204.0    1
190.0    1
125.0    1
166.0    1
Name: previous_rank, dtype: int64

### Examples

#### Top 5 headquarter location in US

In [220]:
f500.loc[f500['country'] == 'USA', 'hq_location'].value_counts().head()

New York, NY      15
Houston, TX        5
Chicago, IL        4
Atlanta, GA        4
Cincinnati, OH     3
Name: hq_location, dtype: int64

#### Top 3 sector in China

In [225]:
f500.loc[f500['country'] == 'China', 'sector'].value_counts().head()

Financials                    22
Energy                        22
Engineering & Construction     8
Motor Vehicles & Parts         7
Materials                      7
Name: sector, dtype: int64

#### Average number of employees for companies headquartered in Japan

In [229]:
f500.loc[f500['country'] == 'Japan', 'employees'].mean()

104564.45098039215